### ISSUE TITLE
Is Screen sharing possible?

### ISSUE THREAD

**Issue by gigabyteservice** [AlexEidt/Vidio#1]
Is it possible that we can combine this with electron js ( [golang to node.js module](https://github.com/sagiegurari/node-go-require)  

Can we recording of enter screen in electron.js based app using webrtc screen sharing api & then stream then recorded video to any rtmp server in real-time.

**Comment by AlexEidt** [comment]
Feel free to fork the project and combine it with any technologies you'd like. Your suggestion sounds like a cool project!

For this repository however, I'd like to keep it as simple and basic as possible, with no dependencies other than `ffmpeg` and `ffprobe` so that it's easily accessible to everyone to use however they'd like.
