### ISSUE TITLE
Support for audio?

### ISSUE THREAD

**Issue by SuperSonicHub1** [AlexEidt/Vidio#2]
This package works great for me and is much faster for my use case than PyAV! Sadly, this package is missing a feature that my Python program had: the ability to copy over audio from the video I'm modifying. Since you're using the FFmpeg CLI directly, the best way to do this would likely be to open up another subprocess to handle audio, and then use [named pipes](https://www.man7.org/linux/man-pages/man7/fifo.7.html) in order to mux video and audio together at once.

**Comment by AlexEidt** [comment]
Copying audio over is actually possible! Just specify the `Audio` attribute in the `Options` struct as shown below and audio will be copied over to the output. I've also made a push to handle errors better by returning them rather than panicking, so there might be some minor tweaks you'll have to make there.

```go
video, err := vidio.NewVideo("input.mp4")
// Error handling...
options := vidio.Options{
	FPS: video.FPS(),
	Bitrate: video.Bitrate(),
	Audio: "input.mp4",
}

writer, err := vidio.NewVideoWriter("output.mp4", video.Width(), video.Height(), &options)
// Error handling...
defer writer.Close()

for video.Read() {
    err := writer.Write(video.FrameBuffer())
	// Error handling...
}
```

Let me know if that solves the issue.

**Comment by SuperSonicHub1** [comment]
Thanks!
